cabal-version: 3.4
name: tomato-slicer
version: 0.1.0.0
synopsis: A tomato timer for JSON-speaking status bars
description:
  See [README.md](https://github.com/sgillespie/tomato-slicer#tomato-slicer) for more details.

homepage: https://github.com/sgillespie/tomato-slicer
bug-reports: https://github.com/sgillespie/tomato-slicer/issues
license: MIT
license-file: LICENSE
author: Sean D Gillespie
maintainer: Sean D Gillespie <sean@mistersg.net>
copyright: 2026 Sean D Gillespie
category: Development
build-type: Simple
tested-with: ghc ==9.10.*
extra-doc-files:
  CHANGELOG.md
  README.md

source-repository head
  type: git
  location: https://github.com/sgillespie/tomato-slicer.git

common common-options
  build-depends:
    base >=4.16 && <5,
    relude,

  mixins:
    base hiding (Prelude),
    relude (Relude as Prelude),
    relude,

  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wderiving-defaults
    -Wmissing-deriving-strategies
    -Wincomplete-uni-patterns
    -Wredundant-constraints
    -Wnoncanonical-monad-instances
    -fhide-source-paths
    -Wmissing-export-lists
    -Wpartial-fields

  default-extensions:
    DeriveAnyClass
    DerivingStrategies
    LambdaCase
    NumericUnderscores
    OverloadedStrings
    RecordWildCards

  default-language: GHC2021

library
  import: common-options
  hs-source-dirs: src
  exposed-modules:
    System.Statusbar.Pomodoro
    System.Statusbar.Pomodoro.Timer

  build-depends:
    aeson,
    clock,
    time,

executable tomato-slicer
  import: common-options
  hs-source-dirs: app
  main-is: Main.hs
  build-depends:
    optparse-applicative,
    tomato-slicer,

  ghc-options:
    -threaded
    -rtsopts
    -with-rtsopts=-N

test-suite tests
  import: common-options
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Main.hs
  other-modules:
    System.Statusbar.Pomodoro.Gen
    System.Statusbar.Pomodoro.TimerTest

  build-depends:
    clock,
    hedgehog,
    hspec,
    hspec-hedgehog,
    time,
    tomato-slicer,

  ghc-options:
    -threaded
    -rtsopts
    -with-rtsopts=-N
